### ISSUE TITLE
全国ランキング機能をつけたい

### ISSUE THREAD

**Issue by akaNetty** [akaNetty/kazanhiko#1]
全国のユーザーのタイムをランキングで表示したいです（１位から５位くらいまで）。ステージを３つ作ったので、それぞれのランキングを取得、表示したいと思っています。
　自分で調べたところ、ユーザ登録の有無や複数モードの有無など、システムによって色々と異なり、正直どれがいいのか分かりません。
　以前、ランキングの記事がある、とじゅんじゅんさんが教えてくださいました、ぜひ読みたいです！

**Comment by TomTomTommy** [comment]
じゅんじゅんがどの記事のことを言ってるのか私には分からないけど、ゆんもランキング機能をつけていたので、参考にした記事がないかゆんにも聞いてみると良いかもです！
直接の解決になっていなくて申し訳ない・・・

**Comment by akaNetty** [comment]
いえ、申し訳ないだなんて！貴重な情報ありがとうございます、Tomさん！

**Comment by akaNetty** [comment]
あやりんさん、記事共有ありがとうございます、参考にさせていただきます！
