### ISSUE TITLE
ランキング機能をつけたら実機ビルドできなくなった

### ISSUE THREAD

**Issue by akaNetty** [akaNetty/kazanhiko#2]
実機でテストしたいのですが、ビルドがうまく行きません。ランキングの実装はできたのですが、実機で動かなくなってしまいました。ランキング実装前はちゃんと実機で動いていました。mac上ではちゃんと動き、ランキングも表示できます。ビルド失敗時、以下の文が出てきました。

CommandInvokationFailure: Unable to install APK to device. Please make sure the Android SDK is installed and is properly configured in the Editor. See the Console for more details. 

　APK、SDKを確認しましたが、合っているみたいで、何が間違っているのか分かりません！

**Comment by Ayarin226** [comment]
なんでだろう、、、
再起動とかしてみたかな？

**Comment by akaNetty** [comment]
はい、してみましたが変化なしでした…

**Comment by Ayarin226** [comment]
こちらの環境だとビルドできたので、SDK周りの問題の可能性が高いです！
端末の再起動も含めて、ビルド環境の確認をもう一度してみてください……！（ランキング機能をコメントアウトしたらビルドできるのか、など）

**Comment by akaNetty** [comment]
分かりました、試してみます！

**Comment by akaNetty** [comment]
端末再起動、PC再起動、ランキングコメントアウト、SDK、JDK、NDKのパス再確認、してもダメでした…
mac上では元気に動いています…

**Comment by akaNetty** [comment]
端末の中に入ってた火山飛行も一度アンインストールしてみましたが、効果はないようです

**Comment by Ayarin226** [comment]
ランキングコメントアウトしてもビルド出来ない？
のならば、Androidビルド環境の問題だと思うな

**Comment by akaNetty** [comment]
なるほど、ビルド環境周辺またいじってみます。

**Comment by Ayarin226** [comment]
ビルド環境は文面だけだとフォローできない部分が多いので、確認して見ても動かないようだったら直接勉強会かSkypeで話しましょう！

**Comment by akaNetty** [comment]
ありがとうございます、勉強会はいけないので、Skypeでお世話になるかもしれません、まずはもう少し自分で確認してみます

**Comment by Ayarin226** [comment]
了解です！
エラーはSDK周りなので、エラー文で検索して色々と試してみるのが良いかも……！
確認しても解決できなかったらまたおしえてください！

**Comment by Ayarin226** [comment]
> Q.ビルド時に以下エラーが発生

> CommandInvokationFailure: Unable to install APK to device. Please make sure the Android SDK is installed and is properly configured in the Editor. See the Console for more details.


> A.ネットで色々調べたが、解決せず。ほぼ同じ構成のプロジェクトのソースコードをフォルダごと差分を取っても特におかしなところなし。結局、PCおよび、スマホの再起動で解決（英語サイトの情報によると、まれにこの障害が発生することがあるらしい。）

ref : https://blog123.tokyo/2017/12/16/unity_kyoukasyo_trouble_ans/

なんだか、このエラー調べてみてもこれだという原因が見つからないね......
再起動をPC、スマホにもおこなってみて欲しいです！！

**Comment by akaNetty** [comment]
再起動してみましたがやはりダメでした。
sdkのtoolsのバージョン下げもしてみてもダメでした

**Comment by akaNetty** [comment]
今日の18:00以降か明日の19:00以降のどこかで、Skypeしていただけませんか？一人での確認に限界が見えてきました…

**Comment by Ayarin226** [comment]
了解！
ちょっと予定確認してみるので待っててね🙏🏻

**Comment by akaNetty** [comment]
ありがとうございます

**Comment by Ayarin226** [comment]
私が今日明日の夜だとかなり遅くなってしまうので、明日の19:00からTomにお願いしました🙏🏻
時間になったらがんばりチャンネルから連絡しますね！

**Comment by akaNetty** [comment]
了解です、ありがとうございます！
