### ISSUE TITLE
ランキング：タイムを送信するとエラーと表示される

### ISSUE THREAD

**Issue by akaNetty** [akaNetty/kazanhiko#3]
タイムを送信すると、オンラインランキング欄のスコアが「エラー」と表示されます。２回目からは「あなたのハイスコア」が「エラー」と表示され、ハイスコア送信ができなくなります。
　mobile backendでは、エラーとなったデータについて、「コントロールパネルの表示範囲を越えているため誤差がある可能性があります」と表示されました。

　ScoreTypeSettingのCustom Formatを変えたり、下の記事を参考にTimeSpanを書き直してみましたがエラーのままでした。

　https://qiita.com/GoldenDrop/items/81e59a78049cc79251a0
　http://yamakami21.hatenablog.com/entry/2015/04/20/185056

　どこが間違っているのかわからないです…

**Comment by Ayarin226** [comment]
`startTime` のあたりをよく見直してみてください！

**Comment by akaNetty** [comment]
見直してみます！

**Comment by Ayarin226** [comment]
`startTime` がグローバル変数として宣言されているのに、新しく関数の中で宣言してから初期化してしまっているのが問題かと思います！
確認してみてください🙏🏻

**Comment by akaNetty** [comment]
なるほど、確認してみます！

**Comment by akaNetty** [comment]
関数中の宣言をやめたらうまく行きました、ありがとうございます！
